// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1-0fkv1BpmUx_JJAxsu3f-UJ0BTp4avI',
    appId: '1:263998496792:web:55810121510d7af4f0236d',
    messagingSenderId: '263998496792',
    projectId: 'time-beater-92596035',
    authDomain: 'time-beater-92596035.firebaseapp.com',
    storageBucket: 'time-beater-92596035.appspot.com',
    measurementId: 'G-94L6W1C16Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbBCwom9thmwIUtE5gOKvA3xM3Byt5uYY',
    appId: '1:263998496792:android:4e8c952ef21e0432f0236d',
    messagingSenderId: '263998496792',
    projectId: 'time-beater-92596035',
    storageBucket: 'time-beater-92596035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM2_by4nipcP4GvuTvTAW2BH6e4c4cEDQ',
    appId: '1:263998496792:ios:1cbfac3c958e49ecf0236d',
    messagingSenderId: '263998496792',
    projectId: 'time-beater-92596035',
    storageBucket: 'time-beater-92596035.appspot.com',
    iosBundleId: 'com.igordokai.flutterFlame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM2_by4nipcP4GvuTvTAW2BH6e4c4cEDQ',
    appId: '1:263998496792:ios:caeba50d09c9b7d0f0236d',
    messagingSenderId: '263998496792',
    projectId: 'time-beater-92596035',
    storageBucket: 'time-beater-92596035.appspot.com',
    iosBundleId: 'com.igordokai.flutterFlame.RunnerTests',
  );
}
